name: C++ CI Workflow

on: [push]

jobs:
  # Job that build on Linux
  ubuntuBuild:
    name: 'ubuntu-18.04'
    runs-on: ubuntu-18.04

    steps:
    # Clone the repository in $GITHUB_WORKSPACE
    - uses: actions/checkout@master
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk expat libexpat1-dev python-all-dev binutils-dev libgcc1:i386 bc libcloog-isl-dev libcap-dev autoconf autoconf-archive libgmp-dev build-essential gcc-multilib g++-multilib pkg-config libmpc-dev libmpfr-dev autopoint gettext liblzma-dev libssl-dev libz-dev

    - name: Build GCC for VxWorks on Ubuntu
      shell: bash
      run: |
        mkdir build
        cd build
        ../build_idjl_gcc_vxworks.sh 
        
    # Upload binaries
    - uses: actions/upload-artifact@master
      with:
        name: idjl-gcc-vworks-ubuntu
        path: build
